AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-apikey1

  Sample SAM Template for sam-apikey1

Parameters:
  StageName:
    Type: String
    Default: dev

Globals:
  Function:
    Timeout: 3
    Runtime: python3.8
    Architectures:
      - x86_64
  Api:
    OpenApiVersion: 3.0.3

Resources:
  ApiGw:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ApiGw
      - ApiGwStage      # ApiGwが生成するAWS::ApiGateway::Stage
    Properties:
      UsagePlanName: !Sub "ExampleUsagePlan-${AWS::StackName}"
      Description: !Sub "for stack ${AWS::StackName}"
      ApiStages:
        - ApiId: !Ref ApiGw
          Stage: !Ref StageName

  ApiUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn:
      - ApiKey
      - ApiUsagePlan
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref ApiUsagePlan

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ApiGw
      - ApiGwStage      # ApiGwが生成するAWS::ApiGateway::Stage
    Properties:
      Name: !Sub "ExampleApiKey-${AWS::StackName}"
      Description: !Sub "for stack ${AWS::StackName}"
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGw
          StageName: !Ref StageName

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Events:
        Hello:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGw
            Path: /hello
            Method: get
            Auth:
              ApiKeyRequired: true
        Hello0:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGw
            Path: /hello0
            Method: get
            # Auth:
            #   ApiKeyRequired: false

  HelloWorldLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: HelloWorldFunction
    Properties:
      RetentionInDays: 7
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref HelloWorldFunction]]

Outputs:
  ApiKeyID:
    Description: Id of API Key Example 1 (not API key)
    Value: !Ref ApiKey
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Hello World function"
    Value: !Sub "https://${ApiGw}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/hello"
